# Generated by Django 2.2.6 on 2019-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddFood',
            fields=[
                ('Food_id', models.AutoField(primary_key=True, serialize=False)),
                ('Food_Type', models.CharField(max_length=100)),
                ('Food_Name', models.CharField(max_length=100)),
                ('Food_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Food_image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
