# Generated by Django 2.2.6 on 2019-10-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewCustomer',
            fields=[
                ('customer_name', models.CharField(max_length=200)),
                ('customer_contact_number', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
