# Generated by Django 2.2.6 on 2019-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFood', '0002_addnewcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewcustomer',
            name='customer_contact_number',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
