# Generated by Django 2.2.6 on 2019-10-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFood', '0005_auto_20191020_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewcustomer',
            name='customer_contact_number',
            field=models.IntegerField(max_length=9999999999999, primary_key=True, serialize=False),
        ),
    ]
