# Generated by Django 2.2.6 on 2019-10-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFood', '0007_auto_20191020_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewcustomer',
            name='customer_id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addnewcustomer',
            name='customer_contact_number',
            field=models.IntegerField(),
        ),
    ]
