# Generated by Django 2.2.6 on 2019-10-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFood', '0008_auto_20191020_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewcustomer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
