# Generated by Django 2.2.6 on 2019-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFood', '0009_auto_20191020_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewcustomer',
            name='username',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
