# Generated by Django 2.2.6 on 2019-10-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFood', '0011_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='Total_Amount_paid',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=50),
        ),
    ]
